#!/bin/bash

rpilist=()

if [ "$1" = "" ];
then
rpilist=( rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpimpw )

else
while [ "$1" != "" ]; do
	rpilist+=( $1 )
	shift
done
fi

for i in "${rpilist[@]}"
do

ping -c 1 $i &>/dev/null
test=$?

if [ "$test" -eq "0" ];

then
	echo $i: alive

else
	echo $i: dead

fi

done
